/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommandsRouteImport } from './routes/commands'
import { Route as ListRouteImport } from './routes/list'
import { Route as OwnedRouteImport } from './routes/owned'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as RanksRouteImport } from './routes/ranks'
import { Route as RosterRouteImport } from './routes/roster'
import { Route as WeaponsRouteImport } from './routes/weapons'
import { Route as RosterIndexRouteImport } from './routes/roster.index'
import { Route as RosterIdRouteImport } from './routes/roster.$id'
import { Route as WeaponsIndexRouteImport } from './routes/weapons.index'
import { Route as WeaponsIdRouteImport } from './routes/weapons.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandsRoute = CommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const ListRoute = ListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnedRoute = OwnedRouteImport.update({
  id: '/owned',
  path: '/owned',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const RanksRoute = RanksRouteImport.update({
  id: '/ranks',
  path: '/ranks',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterRoute = RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const WeaponsRoute = WeaponsRouteImport.update({
  id: '/weapons',
  path: '/weapons',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterIndexRoute = RosterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RosterRoute,
} as any)
const RosterIdRoute = RosterIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RosterRoute,
} as any)
const WeaponsIndexRoute = WeaponsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WeaponsRoute,
} as any)
const WeaponsIdRoute = WeaponsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WeaponsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/commands': typeof CommandsRoute
  '/list': typeof ListRoute
  '/owned': typeof OwnedRoute
  '/premium': typeof PremiumRoute
  '/ranks': typeof RanksRoute
  '/roster': typeof RosterRouteWithChildren
  '/weapons': typeof WeaponsRouteWithChildren
  '/roster/$id': typeof RosterIdRoute
  '/weapons/$id': typeof WeaponsIdRoute
  '/roster/': typeof RosterIndexRoute
  '/weapons/': typeof WeaponsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commands': typeof CommandsRoute
  '/list': typeof ListRoute
  '/owned': typeof OwnedRoute
  '/premium': typeof PremiumRoute
  '/ranks': typeof RanksRoute
  '/roster/$id': typeof RosterIdRoute
  '/weapons/$id': typeof WeaponsIdRoute
  '/roster': typeof RosterIndexRoute
  '/weapons': typeof WeaponsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/commands': typeof CommandsRoute
  '/list': typeof ListRoute
  '/owned': typeof OwnedRoute
  '/premium': typeof PremiumRoute
  '/ranks': typeof RanksRoute
  '/roster': typeof RosterRouteWithChildren
  '/weapons': typeof WeaponsRouteWithChildren
  '/roster/$id': typeof RosterIdRoute
  '/weapons/$id': typeof WeaponsIdRoute
  '/roster/': typeof RosterIndexRoute
  '/weapons/': typeof WeaponsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/commands'
    | '/list'
    | '/owned'
    | '/premium'
    | '/ranks'
    | '/roster'
    | '/weapons'
    | '/roster/$id'
    | '/weapons/$id'
    | '/roster/'
    | '/weapons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/commands'
    | '/list'
    | '/owned'
    | '/premium'
    | '/ranks'
    | '/roster/$id'
    | '/weapons/$id'
    | '/roster'
    | '/weapons'
  id:
    | '__root__'
    | '/'
    | '/commands'
    | '/list'
    | '/owned'
    | '/premium'
    | '/ranks'
    | '/roster'
    | '/weapons'
    | '/roster/$id'
    | '/weapons/$id'
    | '/roster/'
    | '/weapons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommandsRoute: typeof CommandsRoute
  ListRoute: typeof ListRoute
  OwnedRoute: typeof OwnedRoute
  PremiumRoute: typeof PremiumRoute
  RanksRoute: typeof RanksRoute
  RosterRoute: typeof RosterRouteWithChildren
  WeaponsRoute: typeof WeaponsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commands': {
      id: '/commands'
      path: '/commands'
      fullPath: '/commands'
      preLoaderRoute: typeof CommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list': {
      id: '/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof ListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owned': {
      id: '/owned'
      path: '/owned'
      fullPath: '/owned'
      preLoaderRoute: typeof OwnedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranks': {
      id: '/ranks'
      path: '/ranks'
      fullPath: '/ranks'
      preLoaderRoute: typeof RanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster': {
      id: '/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weapons': {
      id: '/weapons'
      path: '/weapons'
      fullPath: '/weapons'
      preLoaderRoute: typeof WeaponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster/': {
      id: '/roster/'
      path: '/'
      fullPath: '/roster/'
      preLoaderRoute: typeof RosterIndexRouteImport
      parentRoute: typeof RosterRoute
    }
    '/roster/$id': {
      id: '/roster/$id'
      path: '/$id'
      fullPath: '/roster/$id'
      preLoaderRoute: typeof RosterIdRouteImport
      parentRoute: typeof RosterRoute
    }
    '/weapons/': {
      id: '/weapons/'
      path: '/'
      fullPath: '/weapons/'
      preLoaderRoute: typeof WeaponsIndexRouteImport
      parentRoute: typeof WeaponsRoute
    }
    '/weapons/$id': {
      id: '/weapons/$id'
      path: '/$id'
      fullPath: '/weapons/$id'
      preLoaderRoute: typeof WeaponsIdRouteImport
      parentRoute: typeof WeaponsRoute
    }
  }
}

interface RosterRouteChildren {
  RosterIdRoute: typeof RosterIdRoute
  RosterIndexRoute: typeof RosterIndexRoute
}

const RosterRouteChildren: RosterRouteChildren = {
  RosterIdRoute: RosterIdRoute,
  RosterIndexRoute: RosterIndexRoute,
}

const RosterRouteWithChildren =
  RosterRoute._addFileChildren(RosterRouteChildren)

interface WeaponsRouteChildren {
  WeaponsIdRoute: typeof WeaponsIdRoute
  WeaponsIndexRoute: typeof WeaponsIndexRoute
}

const WeaponsRouteChildren: WeaponsRouteChildren = {
  WeaponsIdRoute: WeaponsIdRoute,
  WeaponsIndexRoute: WeaponsIndexRoute,
}

const WeaponsRouteWithChildren =
  WeaponsRoute._addFileChildren(WeaponsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommandsRoute: CommandsRoute,
  ListRoute: ListRoute,
  OwnedRoute: OwnedRoute,
  PremiumRoute: PremiumRoute,
  RanksRoute: RanksRoute,
  RosterRoute: RosterRouteWithChildren,
  WeaponsRoute: WeaponsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
